---
title: "Untitled"
author: "am"
date: "2018 M11 11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Week 3 submission
Student questionnaires
math<-read.table(C:\Users\Anna-Mari\Desktop\IODS-project\Data\student-mat.csv)

The data contains information of portuguese students. Their demographic and socioeconomic situation is recorded. Also the use of alcohol and data collected from questionnaires is recorded. The information is combined from sudents, who have conducted the questionnary in theri portuguese and math class.

The data is used to explore the following hypotheses:

H1 Students who have high alcohol consumption, have more absences
H2 alchohol consumption is higher among older students
H3 alchohol consumption decreases as studytime increases
H4 alchohol comsumption is highgest among the students, who have most school absence

H1: a boxplot showing the connection between alcohol consumption and absences is drawn and a logistic model is conducted. Students with high alcohol use have more absences (p<0.05). 

H2: a boxplot and linear logistic model shows, that age and sex effect the odds of high alcohol consumption (p<0.05)

H3: Alcohol comsumption isn't higher among students, who study less. Among female, ths study time is even shorter among students, who consume less alcohol.
